-- 1.
SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID, JOB_ID, SALARY
FROM EMPLOYEES
ORDER BY DEPARTMENT_ID ASC, JOB_ID ASC, SALARY DESC;
-- 2.
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, HIRE_DATE
FROM EMPLOYEES
ORDER BY HIRE_DATE;
-- 3.
SELECT REPLACE(first_name, 'el', '**') FRIST_NAME
FROM EMPLOYEES
WHERE DEPARTMENT_ID > 50;
-- 4.
SELECT LENGTH(UPPER(TRIM('   oracle SQL Programming   ')))
FROM dual;
-- 5.
SELECT CONCAT(
CONCAT(
SUBSTR(TRIM(' Hello, Oracle SQL! '), 1, 5),
':'),
SUBSTR(TRIM(' Hello, Oracle SQL! '), 14, 5))
FROM DUAL;
-- 6.
SELECT 
CONCAT(
LPAD('Data', 10, '-'),
RPAD('Base', 10, '*'))
FROM DUAL;
-- 7.
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE LENGTH(FIRST_NAME) >= 6;
-- 8.
SELECT EMPLOYEE_ID,
MOD(EMPLOYEE_ID, 2)
FROM EMPLOYEES;
-- 9.
SELECT EMPLOYEE_ID, FIRST_NAME
FROM EMPLOYEES
WHERE MOD(EMPLOYEE_ID, 2) = 0;
-- 10.
SELECT FIRST_NAME, SALARY, RPAD('★', ROUND(SALARY / 1000), '★')
FROM EMPLOYEES;
-- 11.
SELECT ROUND(AVG(SALARY), 2)
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 80;
-- 12-1
SELECT JOB_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY JOB_ID;
-- 12-2
SELECT JOB_ID, SUM(SALARY)
FROM EMPLOYEES
GROUP BY SALARY, JOB_ID;
-- 12-3
SELECT DEPARTMENT_ID, MAX(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;
-- 13.
SELECT DEPARTMENT_ID, MAX(SALARY), MIN(SALARY), COUNT(*)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING MAX(SALARY) >= 8000; --
-- 14.
SELECT DEPARTMENT_ID, SUM(SALARY), TRUNC(AVG(SALARY),2), COUNT(*)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(*) >= 20;
-- 15.
SELECT DEPARTMENT_ID, JOB_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID, JOB_ID
HAVING JOB_ID LIKE('%MAN');
-- 16.
SELECT DEPARTMENT_ID, TRUNC(AVG(SALARY), 1)
FROM EMPLOYEES
WHERE DEPARTMENT_ID <= 50
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY) < 10000;